aiapps/aiapps/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('carbike/', include('carbike.urls')),
]

aiapps/carbike/urls.py
from django.urls import path
from . import views

app_name = 'carbike'

urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
]

aiapps/carbike/models.py
from django.db import models
from torch import torch, cuda , nn
from PIL import Image
import io , base64

class Photo(models.Model):
  image = models.ImageField(upload_to='photos')
  device = 'cuda' if cuda.is_available() else 'cpu'

  IMAGE_SIZE = 224 #画像サイズ
  MODEL_FILE_PATH = './carbike/ml_models/model.pth'

  #分類するクラス
  classes = ["car","motorbike"]

  def load_model(self):
    device = self.device
    # パラメータ/ラベルの読み込み
    param = torch.load(self.MODEL_FILE_PATH)

    #モデル定義
    from torchvision import models
    model = models.efficientnet_b7(pretrained=True).to(device)
    # 分類部分の構造を再作成
    model.classifier = torch.nn.Sequential(
                          torch.nn.Dropout(p=0.2, inplace=True),
                          torch.nn.Linear(in_features=2560,
                          out_features=2,
                          bias=True)
                          ).to(device)
    # 重みの再読み込み
    model.load_state_dict(param)
    # 評価モードにする
    model = model.eval()
    return model

  #推定処理
  def predict(self):
    print("Start predict")
    # モデルの読み込み
    device = self.device
    model = self.load_model()

    # 画像データの取得
    img_data = self.image.read()
    img_bin = io.BytesIO(img_data)

    #コマンドラインで渡されたパスをテンソル化
    data = Image.open(img_bin).convert("RGB").resize((self.IMAGE_SIZE,self.IMAGE_SIZE))

    from torchvision import transforms
    data = transforms.Compose([transforms.ToTensor(),
                               transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                                    std=[0.229, 0.224, 0.225]),
    ])(data)
    data = data.unsqueeze_(0).to(device)

    # 予測
    with torch.no_grad():
      outputs = nn.Softmax(dim=1)(model(data))
      pred = self.classes[torch.argmax(outputs)]
      print(pred," ",outputs)

      return pred, outputs
  def image_src(self):
    with self.image.open() as img:
      #画像をBase64の文字列へ変更
      base64_img = base64.b64encode(img.read()).decode()

      return 'data:' + img.file.content_type +';base64,' + base64_img

aiapps/carbike/forms.py
from django import forms

class PhotoForm(forms.Form):
  image = forms.ImageField(widget=forms.FileInput(attrs={'class':'custom-file-input'}))

aiapps/carbike/views.py
from multiprocessing import context
from django.shortcuts import render , redirect
from django.http import HttpResponse
from django.template import loader
from torch import torch
from .forms import PhotoForm
from .models import Photo

def index(request):
  template = loader.get_template('carbike/index.html')
  context = {'form':PhotoForm()}
  return HttpResponse(template.render(context, request))

def predict(request):
  #POST外は無効
  if not request.method == 'POST':
    return redirect('carbike:index')

  form = PhotoForm(request.POST, request.FILES)
  if not form.is_valid():
    raise ValueError('Formが無効です')

  photo = Photo(image = form.cleaned_data['image'])
  predicted, percent = photo.predict()

  template = loader.get_template('carbike/result.html')
  print(template)

  context = {
    'photoname' : photo.image.name,
    'photodata' : photo.image_src(),
    'predicted' : predicted,
    'percentage' : torch.max(percent).item() * 100
  }
  #print(template.render(context, request))
  return HttpResponse(template.render(context, request))

aiapps/carbike/templates/carbike/base.html
<!DOCTYPE html> <html lang="ja">
  <head>
    <meta charset="UTF-8">
    {% load static %}
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'carbike/css/style.css' %}">
    {% bootstrap_javascript %}
    <title>車・バイク判定 | {% block title %} {% endblock %}</title>
  </head>

  <body>

    <nav class="narvar narvar-expand-lg narver-light bg-light">
      <a class="narvar-brand" href="#">画像判定アプリ</a>
    </nav>
    <div class = "container">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

aiapps/carbike/templates/carbike/index.html
{% extends 'carbike/base.html' %}
{% block title%}車・バイク判定アプリメニュー{% endblock %}

{% block content %}
<div>
  <h4 class="mt-4 mb-5 border-bottom">車バイク推定<h4>
  <p>画像ファイルを選択して、推定ボタンクリック</p>
  <form action="{%url 'carbike:predict' %}" method="post" class="form" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <div class="custom-file">
      {{ form.image }}
      <label class="custom-file-label" for="customFile">
        推定したいファイルを選択
      </label>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">推定</button>
  </form>
</div>
{% endblock %}

aiapps/carbike/templates/carbike/result.html
{% extends 'carbike/base.html' %}
{% block title%}車・バイク判定アプリメニュー{% endblock %}

{% block content %}
<div>
  <h4 class="mt-4 mb-5 border-bottom">車バイク推定結果<h4>

  <table class='table'>
    <tbody>
      <tr>
        <td>ファイル名</td>
        <td>{{ photoname }} </td>
      </tr>
      <tr>
        <td>画像データ</td>
        <td><img class='preview-img' src={{ photodata }}></img></td>
      </tr>

      <tr>
        <td>推定ラベル</td>
        <td>{{ predicted }} </td>
      </tr>
      <tr>
        <td>推定確率(%)</td>
        <td>{{percentage}} </td>
      </tr>
    </tbody>
  </table>

  <a href = "{%url 'carbike:index' %}" class= "btn btn-primary">画像選択へ戻る</a>

</div>

{% endblock %}